AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pokemon_ig

  Sample SAM Template for pokemon_ig

Globals:
  Function:
    Timeout: 3

Resources:
  GetPokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: get_data_all_pokemon/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetPokemon:
          Type: Api
          Properties:
            Path: /get_pokemon
            Method: get

  GetOnePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: get_publication/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetOnePokemon:
          Type: Api
          Properties:
            Path: /get_one_pokemon
            Method: get

  AddPokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: post_publication/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        AddPokemon:
          Type: Api
          Properties:
            Path: /add_pokemon
            Method: post

  AddBadgesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: post_badges/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        AddPokemon:
          Type: Api
          Properties:
            Path: /add_badges
            Method: post

  UpdatePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: update_publication/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        UpdatePokemon:
          Type: Api
          Properties:
            Path: /update_pokemon
            Method: put

  DeletePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: delete_publication/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeletePokemon:
          Type: Api
          Properties:
            Path: /delete_pokemon
            Method: delete

  DeleteBadgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: delete_badges/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeletePokemon:
          Type: Api
          Properties:
            Path: /delete_badges
            Method: delete

  RegisterModeratorFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: .
        Handler: register_moderator/app.lambda_handler
        Runtime: python3.12
        Architectures:
          - x86_64
        Events:
          RegisterModerator:
            Type: Api
            Properties:
              Path: /new_moderator
              Method: post

  DeleteReactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: delete_reaction/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeleteReaction:
          Type: Api
          Properties:
            Path: /delete_reaction
            Method: delete

  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: register_user/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeleteReaction:
          Type: Api
          Properties:
            Path: /register_user
            Method: post

  ConfirmRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: confirm_register/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        ConfirmRegister:
          Type: Api
          Properties:
            Path: /confirm_register
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: login/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post

Outputs:
  GetPokemonApi:
    Description: "API Gateway endpoint URL for GetPokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_pokemon/"

  GetOnePokemonApi:
    Description: "API Gateway endpoint URL for GetOnePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod//get_one_pokemon/"

  AddPokemonApi:
    Description: "API Gateway endpoint URL for AddPokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add_pokemon/"

  AddBadgesApi:
    Description: "API Gateway endpoint URL for AddBadges function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add_badges/"

  UpdatePokemonApi:
    Description: "API Gateway endpoint URL for UpdatePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update_pokemon/"

  DeletePokemonApi:
    Description: "API Gateway endpoint URL for DeletePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_pokemon/"

  DeleteBadgesApi:
    Description: "API Gateway endpoint URL for Badge function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_badges/"
    
  RegisterModeratorApi:
    Description: "API Gateway endpoint URL for RegisterModerator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/new_moderator/"

  DeleteReactionApi:
    Description: "API Gateway endpoint URL for DeleteReaction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_reaction/"

  RegisterUserApi:
    Description: "API Gateway endpoint URL for RegisterUser function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register_user/"

  ConfirmRegisterApi:
    Description: "API Gateway endpoint URL for ConfirmRegister function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/confirm_register/"

  LoginApi:
    Description: "API Gateway endpoint URL for Login function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login/"

  GetPokemonFunction:
    Description: "Get Pokemon Lambda Function ARN"
    Value: !GetAtt GetPokemonFunction.Arn

  GetOnePokemonFunction:
    Description: "Get One Pokemon Lambda Function ARN"
    Value: !GetAtt GetOnePokemonFunction.Arn

  AddPokemonFunction:
    Description: "Add Pokemon Lambda Function ARN"
    Value: !GetAtt AddPokemonFunction.Arn

  AddBadgesFunction:
    Description: "Add Badges Lambda Function ARN"
    Value: !GetAtt AddBadgesFunction.Arn

  UpdatePokemonFunction:
    Description: "Update Pokemon Lambda Function ARN"
    Value: !GetAtt UpdatePokemonFunction.Arn

  DeletePokemonFunction:
    Description: "Delete Pokemon Lambda Function ARN"
    Value: !GetAtt DeletePokemonFunction.Arn

  DeleteBadgeFunction:
    Description: "Delete badge Lambda Function ARN"
    Value: !GetAtt DeleteBadgeFunction.Arn
    
  RegisterModeratorFunction:
    Description: "Register Moderator Lambda Function ARN"
    Value: !GetAtt RegisterModeratorFunction.Arn

  DeleteReactionFunction:
    Description: "Delete Reaction Lambda Function ARN"
    Value: !GetAtt  DeleteReactionFunction.Arn

  RegisterUserFunction:
    Description: "Register User Lambda Function ARN"
    Value: !GetAtt  RegisterUserFunction.Arn

  ConfirmRegisterFunction:
    Description: "Confirm Register Lambda Function ARN"
    Value: !GetAtt ConfirmRegisterFunction.Arn

  LoginFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt LoginFunction.Arn

  GetPokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Get Pokemon function"
    Value: !GetAtt GetPokemonFunctionRole.Arn

  GetOnePokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Get One Pokemon function"
    Value: !GetAtt GetOnePokemonFunctionRole.Arn

  AddPokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Add Pokemon function"
    Value: !GetAtt AddPokemonFunctionRole.Arn

  AddBadgesFuctionIamRole:
    Description: "Implicit IAM Role created for Add Badges function"
    Value: !GetAtt AddBadgesFunctionRole.Arn

  UpdatePokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Update Pokemon function"
    Value: !GetAtt UpdatePokemonFunctionRole.Arn

  DeletePokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Pokemon function"
    Value: !GetAtt DeletePokemonFunctionRole.Arn
    
  RegisterModeratorFunctionIamRole:
    Description: "Implicit IAM Role created for Register moderator function"
    Value: !GetAtt RegisterModeratorFunctionRole.Arn

  DeleteReactionFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Reaction function"
    Value: !GetAtt DeleteReactionFunctionRole.Arn

  RegisterUserFunctionIamRole:
    Description: "Implicit IAM Role created for Register User function"
    Value: !GetAtt RegisterUserFunctionRole.Arn

  ConfirmRegisterFucntionIamRole:
    Description: "Implicit IAM Role created for Confirm Register function"
    Value: !GetAtt ConfirmRegisterFunctionRole.Arn

  LoginFunctionIamRole:
    Description: "Implicit IAM Role created for Login function"
    Value: !GetAtt LoginFunctionRole.Arn