AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pokemon_ig

  Sample SAM Template for pokemon_ig

Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to RDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  DBSIONPO:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: sionpo2
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: MySQL
      MasterUsername: admin
      MasterUserPassword: sionpo2024
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId
      PubliclyAccessible: true
      MultiAZ: false

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: sionpoKeys2
      Description: "Secrets for sionpo db"

  CognitoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: cognitoKeys2
      Description: "Secrets for cognito"

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: sionpoPool
      AutoVerifiedAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
          Mutable: true
        - AttributeDataType: String
          Name: picture
          Required: true
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: sionpoClient
      UserPoolId: !Ref UserPool
      GenerateSecret: true

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sionpoBucket
      VersioningConfiguration:
        Status: Enabled

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecretsManagerAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
              - Effect: Allow
                Action:
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:DELETE
                Resource: arn:aws:apigateway:*::/restapis/*
              - Effect: Allow
                Action:
                  - cognito-idp:AdminListGroupsForUser
                  - cognito-idp:AdminAddUserToGroup
                Resource: arn:aws:cognito-idp:us-east-2:058264517160:userpool/us-east-2_NDXZOG7DQ

  GetPokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_data_all_pokemon/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetPokemon:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /get_all_pokemon
            Method: post


  GetOnePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetOnePokemon:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /get_one_pokemon
            Method: get

  AddPokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        AddPokemon:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /add_pokemon
            Method: post

  AddBadgesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post_badges/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        AddPokemon:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /add_badges
            Method: post

  AddReactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post_reaction/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        AddPokemon:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /add_reaction
            Method: post

  UpdatePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        UpdatePokemon:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /update_pokemon
            Method: put

  DeletePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        DeletePokemon:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /delete_pokemon
            Method: delete

  DeleteBadgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_badges/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        DeletePokemon:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /delete_badges
            Method: delete

  DeleteReactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_reaction/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        DeleteReaction:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /delete_reaction
            Method: delete

  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: register_user/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        DeleteReaction:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /register_user
            Method: post

  ConfirmRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: confirm_register/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        ConfirmRegister:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /confirm_register
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: login/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /login
            Method: post

  GetAllUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_all_users/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetAllUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /get_all_users
            Method: get

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_user/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /delete_user
            Method: delete

Outputs:

  LambdaExecutionRoleArn:
    Description: "Implicit IAM Role created for Lambda function"
    Value: !GetAtt LambdaExecutionRole.Arn

  DBSecret:
    Description: "Secret for the RDS instance"
    Value: !Ref DBSecret

  CognitoSecret:
    Description: "Secret for the user pool"
    Value: !Ref CognitoSecret

  S3Bucket:
    Description: "S3 Bucket"
    Value: !Ref S3Bucket


  GetPokemonApi:
    Description: "API Gateway endpoint URL for GetPokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_all_pokemon/"

  GetOnePokemonApi:
    Description: "API Gateway endpoint URL for GetOnePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod//get_one_pokemon/"

  AddPokemonApi:
    Description: "API Gateway endpoint URL for AddPokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add_pokemon/"

  AddBadgesApi:
    Description: "API Gateway endpoint URL for AddBadges function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add_badges/"

  AddReactionApi:
    Description: "API Gateway endpoint URL for AddReaction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add_reaction/"
    
  UpdatePokemonApi:
    Description: "API Gateway endpoint URL for UpdatePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update_pokemon/"

  DeletePokemonApi:
    Description: "API Gateway endpoint URL for DeletePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_pokemon/"

  DeleteBadgesApi:
    Description: "API Gateway endpoint URL for Badge function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_badges/"

  DeleteReactionApi:
    Description: "API Gateway endpoint URL for DeleteReaction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_reaction/"

  RegisterUserApi:
    Description: "API Gateway endpoint URL for RegisterUser function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register_user/"

  ConfirmRegisterApi:
    Description: "API Gateway endpoint URL for ConfirmRegister function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/confirm_register/"

  LoginApi:
    Description: "API Gateway endpoint URL for Login function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login/"

  GetAllUsersApi:
    Description: "API Gateway endpoint URL for GetAllUsers function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_all_users/"

  DeleteUserApi:
    Description: "API Gateway endpoint URL for DeleteUser function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_user/"


  GetAllUsersFunction:
    Description: "Get All Users Lambda Function ARN"
    Value: !GetAtt GetAllUsersFunction.Arn

  GetPokemonFunction:
    Description: "Get Pokemon Lambda Function ARN"
    Value: !GetAtt GetPokemonFunction.Arn

  GetOnePokemonFunction:
    Description: "Get One Pokemon Lambda Function ARN"
    Value: !GetAtt GetOnePokemonFunction.Arn

  AddPokemonFunction:
    Description: "Add Pokemon Lambda Function ARN"
    Value: !GetAtt AddPokemonFunction.Arn

  AddBadgesFunction:
    Description: "Add Badges Lambda Function ARN"
    Value: !GetAtt AddBadgesFunction.Arn

  AddReactionFunction:
    Description: "Add Reaction Lambda Function ARN"
    Value: !GetAtt AddReactionFunction.Arn

  UpdatePokemonFunction:
    Description: "Update Pokemon Lambda Function ARN"
    Value: !GetAtt UpdatePokemonFunction.Arn

  DeletePokemonFunction:
    Description: "Delete Pokemon Lambda Function ARN"
    Value: !GetAtt DeletePokemonFunction.Arn

  DeleteBadgeFunction:
    Description: "Delete badge Lambda Function ARN"
    Value: !GetAtt DeleteBadgeFunction.Arn

  DeleteReactionFunction:
    Description: "Delete Reaction Lambda Function ARN"
    Value: !GetAtt  DeleteReactionFunction.Arn

  RegisterUserFunction:
    Description: "Register User Lambda Function ARN"
    Value: !GetAtt  RegisterUserFunction.Arn

  ConfirmRegisterFunction:
    Description: "Confirm Register Lambda Function ARN"
    Value: !GetAtt ConfirmRegisterFunction.Arn

  LoginFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt LoginFunction.Arn

  DeleteUserFunction:
    Description: "Delete User Lambda Function ARN"
    Value: !GetAtt DeleteUserFunction.Arn
