AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pokemon_ig

  Sample SAM Template for pokemon_ig

Globals:
  Function:
    Timeout: 3

Resources:
  GetPokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_data_all_pokemon/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetPokemon:
          Type: Api
          Properties:
            Path: /get_pokemon
            Method: get
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  GetOnePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetOnePokemon:
          Type: Api
          Properties:
            Path: /get_one_pokemon
            Method: get
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  AddPokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        AddPokemon:
          Type: Api
          Properties:
            Path: /add_pokemon
            Method: post
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  AddBadgesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post_badges/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        AddPokemon:
          Type: Api
          Properties:
            Path: /add_badges
            Method: post
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  AddReactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post_reaction/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        AddPokemon:
          Type: Api
          Properties:
            Path: /add_reaction
            Method: post
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  UpdatePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        UpdatePokemon:
          Type: Api
          Properties:
            Path: /update_pokemon
            Method: put
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  DeletePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeletePokemon:
          Type: Api
          Properties:
            Path: /delete_pokemon
            Method: delete
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  DeleteBadgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_badges/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeletePokemon:
          Type: Api
          Properties:
            Path: /delete_badges
            Method: delete
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  RegisterModeratorFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: register_moderator/
        Handler: app.lambda_handler
        Runtime: python3.12
        Architectures:
          - x86_64
        Events:
          RegisterModerator:
            Type: Api
            Properties:
              Path: /new_moderator
              Method: post
        Policies:
          - PolicyName: LambdaBasicExecution
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - secretsmanager:GetSecretValue
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:*:*:*

  DeleteReactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_reaction/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeleteReaction:
          Type: Api
          Properties:
            Path: /delete_reaction
            Method: delete
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: register_user/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeleteReaction:
          Type: Api
          Properties:
            Path: /register_user
            Method: post
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  ConfirmRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: confirm_register/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        ConfirmRegister:
          Type: Api
          Properties:
            Path: /confirm_register
            Method: post
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: login/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

Outputs:
  GetPokemonApi:
    Description: "API Gateway endpoint URL for GetPokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_pokemon/"

  GetOnePokemonApi:
    Description: "API Gateway endpoint URL for GetOnePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod//get_one_pokemon/"

  AddPokemonApi:
    Description: "API Gateway endpoint URL for AddPokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add_pokemon/"

  AddBadgesApi:
    Description: "API Gateway endpoint URL for AddBadges function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add_badges/"

  AddReactionApi:
    Description: "API Gateway endpoint URL for AddReaction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add_reaction/"
    
  UpdatePokemonApi:
    Description: "API Gateway endpoint URL for UpdatePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update_pokemon/"

  DeletePokemonApi:
    Description: "API Gateway endpoint URL for DeletePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_pokemon/"

  DeleteBadgesApi:
    Description: "API Gateway endpoint URL for Badge function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_badges/"
    
  RegisterModeratorApi:
    Description: "API Gateway endpoint URL for RegisterModerator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/new_moderator/"

  DeleteReactionApi:
    Description: "API Gateway endpoint URL for DeleteReaction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_reaction/"

  RegisterUserApi:
    Description: "API Gateway endpoint URL for RegisterUser function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register_user/"

  ConfirmRegisterApi:
    Description: "API Gateway endpoint URL for ConfirmRegister function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/confirm_register/"

  LoginApi:
    Description: "API Gateway endpoint URL for Login function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login/"

  GetPokemonFunction:
    Description: "Get Pokemon Lambda Function ARN"
    Value: !GetAtt GetPokemonFunction.Arn

  GetOnePokemonFunction:
    Description: "Get One Pokemon Lambda Function ARN"
    Value: !GetAtt GetOnePokemonFunction.Arn

  AddPokemonFunction:
    Description: "Add Pokemon Lambda Function ARN"
    Value: !GetAtt AddPokemonFunction.Arn

  AddBadgesFunction:
    Description: "Add Badges Lambda Function ARN"
    Value: !GetAtt AddBadgesFunction.Arn

  AddReactionFunction:
    Description: "Add Reaction Lambda Function ARN"
    Value: !GetAtt AddReactionFunction.Arn

  UpdatePokemonFunction:
    Description: "Update Pokemon Lambda Function ARN"
    Value: !GetAtt UpdatePokemonFunction.Arn

  DeletePokemonFunction:
    Description: "Delete Pokemon Lambda Function ARN"
    Value: !GetAtt DeletePokemonFunction.Arn

  DeleteBadgeFunction:
    Description: "Delete badge Lambda Function ARN"
    Value: !GetAtt DeleteBadgeFunction.Arn
    
  RegisterModeratorFunction:
    Description: "Register Moderator Lambda Function ARN"
    Value: !GetAtt RegisterModeratorFunction.Arn

  DeleteReactionFunction:
    Description: "Delete Reaction Lambda Function ARN"
    Value: !GetAtt  DeleteReactionFunction.Arn

  RegisterUserFunction:
    Description: "Register User Lambda Function ARN"
    Value: !GetAtt  RegisterUserFunction.Arn

  ConfirmRegisterFunction:
    Description: "Confirm Register Lambda Function ARN"
    Value: !GetAtt ConfirmRegisterFunction.Arn

  LoginFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt LoginFunction.Arn

  GetPokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Get Pokemon function"
    Value: !GetAtt GetPokemonFunctionRole.Arn

  GetOnePokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Get One Pokemon function"
    Value: !GetAtt GetOnePokemonFunctionRole.Arn

  AddPokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Add Pokemon function"
    Value: !GetAtt AddPokemonFunctionRole.Arn

  AddBadgesFunctionIamRole:
    Description: "Implicit IAM Role created for Add Badges function"
    Value: !GetAtt AddBadgesFunctionRole.Arn

  AddReactionFunctionIamRole:
    Description: "Implicit IAM Role created for Add Reaction function"
    Value: !GetAtt AddReactionFunctionRole.Arn

  UpdatePokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Update Pokemon function"
    Value: !GetAtt UpdatePokemonFunctionRole.Arn

  DeletePokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Pokemon function"
    Value: !GetAtt DeletePokemonFunctionRole.Arn
    
  RegisterModeratorFunctionIamRole:
    Description: "Implicit IAM Role created for Register moderator function"
    Value: !GetAtt RegisterModeratorFunctionRole.Arn

  DeleteReactionFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Reaction function"
    Value: !GetAtt DeleteReactionFunctionRole.Arn

  RegisterUserFunctionIamRole:
    Description: "Implicit IAM Role created for Register User function"
    Value: !GetAtt RegisterUserFunctionRole.Arn

  ConfirmRegisterFucntionIamRole:
    Description: "Implicit IAM Role created for Confirm Register function"
    Value: !GetAtt ConfirmRegisterFunctionRole.Arn

  LoginFunctionIamRole:
    Description: "Implicit IAM Role created for Login function"
    Value: !GetAtt LoginFunctionRole.Arn
