AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pokemon_ig

  Sample SAM Template for pokemon_ig

Globals:
  Function:
    Timeout: 3

Resources:
  GetPokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_data_all_pokemon/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetPokemon:
          Type: Api
          Properties:
            Path: /get_pokemon
            Method: get

  GetOnePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetOnePokemon:
          Type: Api
          Properties:
            Path: /get_one_pokemon
            Method: get

  AddPokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        AddPokemon:
          Type: Api
          Properties:
            Path: /add_pokemon
            Method: post

  AddBadgesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post_badges/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        AddPokemon:
          Type: Api
          Properties:
            Path: /add_badges
            Method: post

  UpdatePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        UpdatePokemon:
          Type: Api
          Properties:
            Path: /update_pokemon
            Method: put

  DeletePokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_publication/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        DeletePokemon:
          Type: Api
          Properties:
            Path: /delete_pokemon
            Method: delete

Outputs:
  GetPokemonApi:
    Description: "API Gateway endpoint URL for GetPokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_pokemon/"

  GetOnePokemonApi:
    Description: "API Gateway endpoint URL for GetOnePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod//get_one_pokemon/"

  AddPokemonApi:
    Description: "API Gateway endpoint URL for AddPokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add_pokemon/"

  AddBadgesApi:
    Description: "API Gateway endpoint URL for AddBadges function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add_badges/"

  UpdatePokemonApi:
    Description: "API Gateway endpoint URL for UpdatePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update_pokemon/"

  DeletePokemonApi:
    Description: "API Gateway endpoint URL for DeletePokemon function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_pokemon/"

  GetPokemonFunction:
    Description: "Get Pokemon Lambda Function ARN"
    Value: !GetAtt GetPokemonFunction.Arn

  GetOnePokemonFunction:
    Description: "Get One Pokemon Lambda Function ARN"
    Value: !GetAtt GetOnePokemonFunction.Arn

  AddPokemonFunction:
    Description: "Add Pokemon Lambda Function ARN"
    Value: !GetAtt AddPokemonFunction.Arn

  AddBadgesFunction:
    Description: "Add Badges Lambda Function ARN"
    Value: !GetAtt AddBadgesFunction.Arn

  UpdatePokemonFunction:
    Description: "Update Pokemon Lambda Function ARN"
    Value: !GetAtt UpdatePokemonFunction.Arn

  DeletePokemonFunction:
    Description: "Delete Pokemon Lambda Function ARN"
    Value: !GetAtt DeletePokemonFunction.Arn

  GetPokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Get Pokemon function"
    Value: !GetAtt GetPokemonFunctionRole.Arn

  GetOnePokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Get One Pokemon function"
    Value: !GetAtt GetOnePokemonFunctionRole.Arn

  AddPokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Add Pokemon function"
    Value: !GetAtt AddPokemonFunctionRole.Arn

  AddBadgesFuctionIamRole:
    Description: "Implicit IAM Role created for Add Badges function"
    Value: !GetAtt AddBadgesFunctionRole.Arn

  UpdatePokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Update Pokemon function"
    Value: !GetAtt UpdatePokemonFunctionRole.Arn

  DeletePokemonFunctionIamRole:
    Description: "Implicit IAM Role created for Delete Pokemon function"
    Value: !GetAtt DeletePokemonFunctionRole.Arn
