name: Build
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened, closed]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Debug Info
        run: |
          echo "Running on branch ${{ github.ref }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event path: ${{ github.event_path }}"
          cat ${{ github.event_path }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
