name: Build
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r update_publication/requirements.txt
          pip install -r get_publication/requirements.txt
          pip install -r get_data_all_pokemon/requirements.txt
          pip install -r post_publication/requirements.txt
          pip install -r delete_badges/requirements.txt
          pip install -r delete_publication/requirements.txt
          pip install -r post_badges/requirements.txt
          pip install -r post_reaction/requirements.txt
          pip install -r register_moderator/requirements.txt
          pip install -r register_user/requirements.txt
          pip install -r confirm_register/requirements.txt
          pip install -r delete_reaction/requirements.txt
          pip install -r login/requirements.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: sonarcloud
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r update_publication/requirements.txt
          pip install -r get_publication/requirements.txt
          pip install -r get_data_all_pokemon/requirements.txt
          pip install -r post_publication/requirements.txt
          pip install -r delete_badges/requirements.txt
          pip install -r delete_publication/requirements.txt
          pip install -r post_badges/requirements.txt
          pip install -r post_reaction/requirements.txt
          pip install -r register_moderator/requirements.txt
          pip install -r register_user/requirements.txt
          pip install -r confirm_register/requirements.txt
          pip install -r delete_reaction/requirements.txt
          pip install -r login/requirements.txt

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name pokemonIg --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
